name: course_online
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  auto_route: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.5.0
  build_runner:

flutter:
  uses-material-design: true
